// const Strings = {
    
//     // Password
//     password:'Password',
//     passwordPlaceholer: "Enter password",
//     passwordLengthMessage: 'Password must be at least 6 characters',
//     passwordConfirm: 'Passwords do not match',
//     newPassword: "Create New Password",
//     uniquePassword: "Your new password must be different from previously used password.",
//     retypePassword: "Re-type password",
//     forgotPassword: "Forgot Password?",
    
//     // Email
//     email: "Email",
//     emailPleaceholder: "Enter email",
//     emailVerificicationMessage: "Please enter your email address to receive a verification code. ",
//     emailError: 'Invalid email address',
//     invalidEmail: 'Invalid email address',
//     userInfo: "Error getting user info",
//     otp: "OTP Verification",
//     verify: "Verify",
//     name: "Enter name",
//     nameMessage: 'Name must be at least 3 characters',
    
//     // Account
//     noAccount: "Already haven't an account?",
//     haveAccount: "Already haven an account?" ,
//     otp: "OTP code ",
//     enterOTP: "Please enter the 4 digit code sent to ",
//     resend: "Resend code to ",
//     hoursError: "Maximum hours must be greater than minimum hour",
//     selectPhoto: 'Take a new photo or select one from your gallery.',
//     gallery: 'Gallery',
//     camera: 'Camera',
    
//     // Alerts
//     camPermissionTitle: 'Camera Permission',
//     camPermissionMsg: 'App needs camera permission',
//     camError: 'cameraNotAvailable',
//     camIssue: 'cameraIssue',
//     stgPermissionTitle: 'External Storage Write Permission',
//     stgPermissionMsg: 'App needs write permission',
//     userCancelled: 'userCancelledCameraPicker',
//     permissionError: 'permissionNotSatisfied',
    
//     // Input Fields
//     emptyField: "All fields are mandatory",
    
//     // Boat
//     scanImage: "Scan Your License",
//     boatResume: "Boat Resume",
//     addMoreInfo: "Add Boat Image & More Information",
//     watercraftType: "Watercraft types",
//     craftName: "Craft name",
//     maxHours: "Max hours",
//     minHours: 'Min Hour',
//     addDescripiton: "Add description",
//     addImageLabel: "Add boat images",
//     addImage: "Add Image",
//     gustCapacity: "Gust Capacity",
//     rendPerHour: "Rent per hour",
//     perHour: "per hour",
//     boatExperience: "Boating Experience",
//     boatExperienceLabel: "Experience(years)",
//     experience: "Experience",
//     aboutBoatExperience: "Write about your boating experience",
//     outboard: "Outboard",
//     inboard: 'Inboard/Ourboard',
//     singleScrew: 'Inboard single propeller / screw',
//     doubleScrew: 'Inboard two propeller / screw',
//     singleScrewWithThrustor: 'Inboard single propeller / screw with bow thrustor',
//     doubleScrewWithThrustor: 'Inboard two propeller / screw with bow thrustor',
//     sportFishing: 'Sport fishing',
//     sportFishingWithOutriggers: 'Sport fishing with outriggers',
//     racing: 'Racing',
//     sailing: 'Day Sailing',
//     crusing: 'Crusing',
//     passage: 'Passage making',
//     delivery: 'Delivery',
//     powerBoat: "Power Boat",
//     sailBoat: "SailBoat",
//     powerType: "Type of Power",
//     loaSail: "Sailboat LOA",
//     loaSailPlaceholder: "56ft",
//     loaPowerBoat: "Power Boat LOA",
//     loaPowerBoatPlaceholder: "56ft",
//     typesOfSailing: "Type of Sailing",
//     capLicence: "Captain License",
//     fullName: 'Full name',
//     addressOne: 'Address 1',
//     addressTwo: 'Address 2',
//     city: 'City',
//     state: 'State',
//     credential: 'Credential',
//     issueDate: "Issue date:",
//     credentialType: "Credential type:",
//     exDate: "Expiry date:",
//     front: "Front",
//     addScan:"Add Scan",
//     back:"Back",
//     // Buttons
//     login : 'Login',
//     signUp : 'Sign Up',
//     continue: "Continue",
//     saveButton: "Save",
//     send: "Send",
//     bookingDetails: "Booking Details",
//     duration:"Duration",
//     guestNo:"Guest Number",
//     from:"From",
//     to:"To",
//     activities:"Activities",
//     accepted:"Accepted",
//     reject:"Reject",
//     pending:"Pending",
//     past:"Past",
//     myBookings:"My Bookings",
//     noBookings: "There are no bookings",
//     today:"Today",
//     monthly:"Monthly",
//     yearly:"Yearly",
//     start:"Start",
//     end:"End",
//     bookings:"Bookings",
//     myWallet:"My Wallet",
//     totalBalance: "Total Balance",
//     userError: "Error getting user info",
//     totalEarning: "Total Earning",
//     search: "Search",
//     chooseImage: "Choose Image",
//     hours: "hours",
//     guest: 'guest',
//     rejected: 'Rejected',
//     paid: 'Paid',
//     guestNumber: "Guest number:",
//     payout: "Payout:",
//     completed: "Completed",
//     pickupLocation:"Send Pickup Location"
    
// }
// export default Strings
const Strings = {
    
    // Password
    password:'كلمة المرور',
    passwordPlaceholer: "أدخل كلمة المرور",
    passwordLengthMessage: 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل',
    passwordConfirm: 'كلمة المرور غير مطابقة',
    newPassword: "إنشاء كلمة مرور جديدة",
    uniquePassword: "يجب أن تكون كلمة المرور الجديدة مختلفة عن كلمة المرور المستخدمة سابقًا.",
    retypePassword: "أعد إدخال كلمة السر",
    forgotPassword: "هل نسيت كلمة السر؟",
    
    // Email
    email: "البريد الالكتروني",
    emailPleaceholder: "أدخل البريد الالكتروني",
    emailVerificicationMessage: "الرجاء إدخال عنوان بريدك الإلكتروني لتلقي رمز التحقق ",
    emailError: 'عنوان البريد الإلكتروني غير صالح',
    invalidEmail: 'عنوان البريد الإلكتروني غير صالح',
    userInfo: "حدث خطأ أثناء الحصول على معلومات المستخدم",
    otp: "التحقق من OTP",
    verify: "تحقق",
    name: "أدخل الاسم",
    nameMessage: 'يجب أن يتكون الاسم من 3 أحرف على الأقل',
    
    // Account
    noAccount: "هل لديك حساب؟",
    haveAccount: "هل لديك حساب" ,
    otp: "رمز التحقق ",
    enterOTP: "الرجاء إدخال الرمز المكون من 4 أرقام المرسل إلى",
    resend: "إعادة إرسال الرمز ",
    hoursError: "يجب أن يكون الحد الأقصى للساعات أكبر من الحد الأدنى للساعة",
    selectPhoto: 'التقط صورة جديدة أو اختر من معرض الصور الخاص بك.',
    gallery: 'معرض الصور',
    camera: 'الكاميرا',
    
    // Alerts
    camPermissionTitle: 'السماح للوصول للكاميرا',
    camPermissionMsg: 'يحتاج التطبيق إذن الوصول للكاميرا',
    camError: 'لايوجد كاميرا',
    camIssue: 'عطل في الكاميرا',
    stgPermissionTitle: 'إذن الكتابة للتخزين الخارجي',
    stgPermissionMsg: 'يحتاج التطبيق إلى إذن الكتابة',
    userCancelled: 'المستخدم قام بإلغاء محدد الصور',
    permissionError: 'فشل في الحصول على الإذن',
    
    // Input Fields
    emptyField: "جميع الحقول إلزامية",
    
    // Boat
    scanImage: "مسح الرخصة الخاص بك",
    boatResume: "سيرة المركبة الذاتية",
    addMoreInfo: "إضافة صور للمركبة ومعلوماتها",
    watercraftType: "نوع المركبة",
    craftName: "إسم المركبة",
    maxHours: "الحد الأقصى للساعات",
    minHours: 'الحد الأدنى للساعات',
    addDescripiton: "إضافة وصف",
    addImageLabel: "إضافة صور المركبة",
    addImage: "إضافة صورة",
    gustCapacity: "أقصى عدد للركاب",
    rendPerHour: "تأجير بالساعة",
    perHour: "بالساعة",
    boatExperience: "تجربة الإبحار",
    boatExperienceLabel: "الخبرة(سنوات)",
    experience: "الخبرة",
    aboutBoatExperience: "اكتب عن خبرتك في الإبحار",
    outboard: "خارجي",
    inboard: 'داخلي/خارجي',
    singleScrew: 'Inboard single propeller / screw',
    doubleScrew: 'Inboard two propeller / screw',
    singleScrewWithThrustor: 'Inboard single propeller / screw with bow thrustor',
    doubleScrewWithThrustor: 'Inboard two propeller / screw with bow thrustor',
    sportFishing: 'صيد الأسماك',
    sportFishingWithOutriggers: 'Sport fishing with outriggers',
    racing: 'سباق',
    sailing: 'رحلة بحرية',
    crusing: 'رحلة بحرية',
    passage: 'Passage making',
    delivery: 'توصيل',
    powerBoat: "Power Boat",
    sailBoat: "قارب إبحار",
    powerType: "Type of Power",
    loaSail: "اتفاقية الإبحار",
    loaSailPlaceholder: "56 قدم",
    loaPowerBoat: "Power Boat LOA",
    loaPowerBoatPlaceholder: "56ft",
    typesOfSailing: "أنواع الإبحار",
    capLicence: "رخصة الكابتن",
    fullName: 'الإسم الكامل',
    addressOne: 'العنوان 1',
    addressTwo: 'العنوان 2',
    city: 'المدينة',
    state: 'المنقطة',
    credential: 'الوثيقة',
    issueDate: "تاريخ الإصدار:",
    credentialType: "نوع الوثيقة:",
    exDate: "تاريخ الإنتهاء",
    front: "من الأمام",
    addScan:"مسح آخر",
    back:"من الخلف",
    // Buttons
    login : 'تسجيل دخول',
    signUp : 'إنشاء حساب جديد',
    continue: "تابع",
    saveButton: "حفظ",
    send: "إرسال",
    bookingDetails: "تفاصيل الحجز",
    duration:"المدة",
    guestNo:"عدد الركاب",
    from:"من",
    to:"إلى",
    activities:"الأنشطة",
    accepted:"مقبول",
    reject:"مرفوض",
    pending:"معلق",
    past:"Past",
    myBookings:"حجوزاتي",
    noBookings: "لايوجد حجوزات",
    today:"اليوم",
    monthly:"شهري",
    yearly:"سنوي",
    start:"بداية",
    end:"نهاية",
    bookings:"حجوزات",
    myWallet:"المحفظة",
    totalBalance: "إجمالي الرصيد",
    userError: "حدث خطأ أثناء الحصول على معلومات المستخدم",
    totalEarning: "إجمالي الأرباح",
    search: "البحث",
    chooseImage: "إختر صورة",
    hours: "ساعات",
    guest: 'ركاب',
    rejected: 'مرفوض',
    paid: 'مدفوع',
    guestNumber: "عدد الركاب:",
    payout: "Payout:",
    completed: "مكتمل",
    pickupLocation:"أرسل موقع الإركاب"
    
}
export default Strings